web:
  build: .
  links:
    - db
  log_driver: gelf
  log_opt:
    gelf-address: udp://localhost:12201

db:
  image: postgres:9.3.5
  log_driver: gelf
  log_opt:
    gelf-address: udp://localhost:12201

